-- MySQL Script generated by MySQL Workbench
-- mar 21 mar 2023 15:48:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PizzeriaMammaMia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PizzeriaMammaMia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PizzeriaMammaMia` DEFAULT CHARACTER SET utf8mb3 ;
USE `PizzeriaMammaMia` ;

-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Shop` (
  `Shop_id` INT NOT NULL AUTO_INCREMENT,
  `Shop_address` VARCHAR(45) NOT NULL,
  `Shop_zip` INT NOT NULL,
  `Shop_city` VARCHAR(45) NULL DEFAULT NULL,
  `Shop_state` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Shop_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`ClientState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`ClientState` (
  `ClientState_id` INT NOT NULL AUTO_INCREMENT,
  `ClientState_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ClientState_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`ClientCity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`ClientCity` (
  `ClientCity_id` INT NOT NULL AUTO_INCREMENT,
  `ClientCity_name` VARCHAR(45) NOT NULL,
  `ClientState_ClientState_id` INT NOT NULL,
  PRIMARY KEY (`ClientCity_id`),
  INDEX `fk_ClientCity_ClientState1_idx` (`ClientState_ClientState_id` ASC) VISIBLE,
  CONSTRAINT `fk_ClientCity_ClientState1`
    FOREIGN KEY (`ClientState_ClientState_id`)
    REFERENCES `PizzeriaMammaMia`.`ClientState` (`ClientState_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Clients` (
  `Client_id` INT NOT NULL AUTO_INCREMENT,
  `Client_name` VARCHAR(45) NOT NULL,
  `Client_fname` VARCHAR(45) NOT NULL,
  `Client_zip` INT NOT NULL,
  `Client_tel` INT NOT NULL,
  `ClientCity_ClientCity_id` INT NOT NULL,
  `ClientCity_ClientCity_ClientState_id` INT NOT NULL,
  PRIMARY KEY (`Client_id`),
  INDEX `fk_Client_ClientCity1_idx` (`ClientCity_ClientCity_id` ASC, `ClientCity_ClientCity_ClientState_id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_ClientCity1`
    FOREIGN KEY (`ClientCity_ClientCity_id`)
    REFERENCES `PizzeriaMammaMia`.`ClientCity` (`ClientCity_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Orders` (
  `Order_id` INT NOT NULL AUTO_INCREMENT,
  `Order_type` ENUM('Delivery', 'AtPlace') NOT NULL,
  `Order_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Order_qty_Pizzas` INT NULL DEFAULT NULL,
  `Order_qty_Drinks` INT NULL DEFAULT NULL,
  `Order_qty_Burgers` INT NULL DEFAULT NULL,
  `Order_price` DOUBLE NOT NULL,
  `Shop_Shop_id` INT NOT NULL,
  `Client_Client_id` INT NOT NULL,
  PRIMARY KEY (`Order_id`),
  INDEX `fk_Order_Shop1_idx1` (`Shop_Shop_id` ASC) VISIBLE,
  INDEX `fk_Orders_Client1_idx` (`Client_Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Shop1`
    FOREIGN KEY (`Shop_Shop_id`)
    REFERENCES `PizzeriaMammaMia`.`Shop` (`Shop_id`),
  CONSTRAINT `fk_Orders_Client1`
    FOREIGN KEY (`Client_Client_id`)
    REFERENCES `PizzeriaMammaMia`.`Clients` (`Client_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Burgers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Burgers` (
  `Burgers_id` INT NOT NULL AUTO_INCREMENT,
  `Burgers_name` VARCHAR(45) NOT NULL,
  `Burgers_description` VARCHAR(45) NOT NULL,
  `Burgers_image` BLOB NULL DEFAULT NULL,
  `Burgers_price` DOUBLE NOT NULL,
  `Orders_Order_id` INT NOT NULL,
  `Orders_Client_id` INT NOT NULL,
  PRIMARY KEY (`Burgers_id`),
  INDEX `fk_Burgers_Orders1_idx` (`Orders_Order_id` ASC, `Orders_Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Burgers_Orders1`
    FOREIGN KEY (`Orders_Order_id`)
    REFERENCES `PizzeriaMammaMia`.`Orders` (`Order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Categories` (
  `Categories_id` INT NOT NULL AUTO_INCREMENT,
  `Categories_names` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Categories_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Employee` (
  `Employee_id` INT NOT NULL AUTO_INCREMENT,
  `Employee_name` VARCHAR(45) NOT NULL,
  `Employee_fname` VARCHAR(45) NOT NULL,
  `Employee_tel` INT NOT NULL,
  `Employee_NIF` VARCHAR(10) NOT NULL,
  `Employee_type` ENUM('Cooker', 'DeliveryMan') NOT NULL,
  `Shop_Shop_id` INT NOT NULL,
  PRIMARY KEY (`Employee_id`),
  INDEX `fk_Employee_Shop1_idx` (`Shop_Shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Shop1`
    FOREIGN KEY (`Shop_Shop_id`)
    REFERENCES `PizzeriaMammaMia`.`Shop` (`Shop_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Delivery` (
  `Delivery_id` INT NOT NULL AUTO_INCREMENT,
  `Delivery_worker` VARCHAR(45) NOT NULL,
  `Delivery_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Employee_Employee_id` INT NOT NULL,
  `Employee_Shop_Shop_id` INT NOT NULL,
  PRIMARY KEY (`Delivery_id`),
  INDEX `fk_Delivery_Employee1_idx1` (`Employee_Employee_id` ASC, `Employee_Shop_Shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_Delivery_Employee1`
    FOREIGN KEY (`Employee_Employee_id`)
    REFERENCES `PizzeriaMammaMia`.`Employee` (`Employee_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Drinks` (
  `Drinks_id` INT NOT NULL AUTO_INCREMENT,
  `Drinks_name` VARCHAR(45) NOT NULL,
  `Drinks_description` VARCHAR(45) NOT NULL,
  `Drinks_image` BLOB NULL DEFAULT NULL,
  `Drinks_price` DOUBLE NOT NULL,
  `Orders_Order_id` INT NOT NULL,
  `Orders_Client_id` INT NOT NULL,
  PRIMARY KEY (`Drinks_id`),
  INDEX `fk_Drinks_Orders1_idx` (`Orders_Order_id` ASC, `Orders_Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Drinks_Orders1`
    FOREIGN KEY (`Orders_Order_id`)
    REFERENCES `PizzeriaMammaMia`.`Orders` (`Order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PizzeriaMammaMia`.`Pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PizzeriaMammaMia`.`Pizzas` (
  `Pizzas_id` INT NOT NULL AUTO_INCREMENT,
  `Pizzas_name` VARCHAR(45) NOT NULL,
  `Pizzas_description` VARCHAR(45) NOT NULL,
  `Pizzas_image` BLOB NULL DEFAULT NULL,
  `Pizzas_price` DOUBLE NOT NULL,
  `Orders_Order_id` INT NOT NULL,
  `Orders_Client_id` INT NOT NULL,
  `Categories_Categories_id` INT NOT NULL,
  PRIMARY KEY (`Pizzas_id`),
  INDEX `fk_Pizzas_Orders1_idx` (`Orders_Order_id` ASC, `Orders_Client_id` ASC) VISIBLE,
  INDEX `fk_Pizzas_Categories1_idx` (`Categories_Categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pizzas_Categories1`
    FOREIGN KEY (`Categories_Categories_id`)
    REFERENCES `PizzeriaMammaMia`.`Categories` (`Categories_id`),
  CONSTRAINT `fk_Pizzas_Orders1`
    FOREIGN KEY (`Orders_Order_id`)
    REFERENCES `PizzeriaMammaMia`.`Orders` (`Order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;

-- Insert data 

-- ClientState 1

INSERT INTO `PizzeriaMammaMia`.`ClientState` (`ClientState_name`) VALUES
('New Jersey'),
('California'),
('Illinois'),
('Texas'),
('Arizona'),
('Pennsilvania'),
('Colorado'),
('Delaware'),
('Florida'),
('Georgia');

-- ClientCity 2

INSERT INTO `PizzeriaMammaMia`.`ClientCity` (`ClientCity_name`, `ClientState_ClientState_id`) VALUES
('New York City', 1),
('Los Angeles', 2),
('Chicago', 3),
('Houston', 4),
('Phoenix', 5),
('Philadelphia', 6),
('San Antonio', 4),
('San Diego', 2),
('Dallas', 4),
('San Jose', 2);

-- Client 3

INSERT INTO `PizzeriaMammaMia`.`Clients` 
(`Client_name`, `Client_fname`, `Client_zip`, `Client_tel`, `ClientCity_ClientCity_id`, `ClientCity_ClientCity_ClientState_id`) 
VALUES 
('John', 'Doe', 12345, 5551234, 1, 1),
('Jane', 'Doe', 54321, 5554321, 2, 2),
('Bob', 'Smith', 67890, 5557890, 3, 3),
('Alice', 'Smith', 09876, 5550987, 4, 4),
('Tom', 'Jones', 11111, 5551111, 5, 5),
('Mary', 'Johnson', 22222, 5552222, 6, 6),
('David', 'Brown', 33333, 5553333, 7, 4),
('Sarah', 'Davis', 44444, 5554444, 8, 2),
('Michael', 'Wilson', 55555, 5555555, 9, 4),
('Laura', 'Miller', 66666, 5556666, 10, 2);

-- shop 4

INSERT INTO `PizzeriaMammaMia`.`Shop` (`Shop_address`, `Shop_zip`, `Shop_city`, `Shop_state`) VALUES
('123 Main St', 10001, 'New York', 'NY'),
('456 Maple Ave', 60611, 'Chicago', 'IL'),
('789 Oak St', 90012, 'Los Angeles', 'CA'),
('1011 Pine St', 30303, 'Atlanta', 'GA'),
('1213 Elm St', 75201, 'Dallas', 'TX'),
('1415 Walnut St', 19103, 'Philadelphia', 'PA'),
('1617 Broadway', 10019, 'New York', 'NY'),
('1819 Market St', 19103, 'Philadelphia', 'PA'),
('2021 Michigan Ave', 60616, 'Chicago', 'IL'),
('2223 Sunset Blvd', 90027, 'Los Angeles', 'CA');


-- Employee 5

INSERT INTO `Employee` ( `Employee_name`, `Employee_fname`, `Employee_tel`, `Employee_NIF`, `Employee_type`,`Shop_Shop_id`) VALUES 
('John', 'Doe', 5551234, '123456789A', 'Cooker', 1),
('Jane', 'Doe', 5555678, '987654321B', 'DeliveryMan', 1),
('Mark', 'Smith', 5554321, '456789123C', 'Cooker', 2),
('Mary', 'Smith', 5558765, '321654987D', 'DeliveryMan', 2),
('David', 'Lee', 5552468, '159263478E', 'Cooker', 3),
('Lucy', 'Chen', 5551357, '852369741F', 'DeliveryMan', 3),
('Mike', 'Johnson', 5558765, '741852963G', 'Cooker', 4),
('Sarah', 'Brown', 5553692, '369258147H', 'DeliveryMan', 4),
('Tom', 'Wong', 5556803, '258147369I', 'Cooker', 5),
('Alice', 'Liu', 5551234, '147258369J', 'DeliveryMan', 5);

-- Delivery 6 

INSERT INTO `PizzeriaMammaMia`.`Delivery` ( `Delivery_worker`, `Delivery_time`, `Employee_Employee_id`, `Employee_Shop_Shop_id`)
VALUES ('Jane Doe', '2022-03-19 12:30:00',2,1),
       ('Mary Smith', '2022-03-19 14:45:00',4,2 ),
       ('Lucy Chen', '2022-03-19 16:15:00',6,3),
       ('Sarah Brown', '2022-03-19 17:30:00',8,4 ),
       ('Alice Liu', '2022-03-19 19:00:00',10,5 );

-- orders 7

INSERT INTO `PizzeriaMammaMia`.`Orders` 
(`Order_type`, `Order_qty_Pizzas`, `Order_qty_Drinks`,`Order_qty_Burgers`,`Order_price`, `Shop_Shop_id`, `Client_Client_id`) 
VALUES 
('Delivery', 2,2,0, 20.50, 1, 1),
('AtPlace', 3,0,0 ,30.75, 2, 2),
('Delivery', 0,2,2, 15.99, 3, 3),
('AtPlace', 4,4,0, 40.00, 4, 4),
('Delivery', 1,1,1, 23.50, 5, 5),
('AtPlace', 1,2,1, 12.25, 6, 6),
('Delivery', 3,2,0, 35.99, 7, 4),
('AtPlace', 2,2,0, 20.00,  8, 2),
('Delivery', 1,1,0, 10.99,  9, 4),
('AtPlace', 4,2,1, 50.50, 10, 2);

-- Client 1 : 2 pizzas 2 beguda 0 burger
-- Client 2 : 3 pizzas 0 beguda 0 burger
-- Client 3 : 0 pizzas 2 beguda 2 burger
-- Client 4 : 4 pizzas 4 beguda 0 burger
-- Client 5 : 1 pizzas 1 beguda 1 burger
-- Client 6 : 1 pizzas 2 beguda 1 burger
-- Client 7 : 3 pizzas 2 beguda 0 burger
-- Client 8 : 2 pizzas 2 beguda 0 burger
-- Client 9 : 1 pizzas 1 beguda 0 burger
-- Client 10 : 4 pizzas 2 beguda 1 burger

-- Drinks 8

INSERT INTO `PizzeriaMammaMia`.`Drinks` (`Drinks_name`, `Drinks_description`, `Drinks_image`, `Drinks_price`, `Orders_Order_id`, `Orders_Client_id`)
VALUES 
('Coke', 'Refreshing carbonated soft drink', NULL, 1.99, 1, 1),
('Sprite', 'Lemon-lime flavored carbonated soft drink', NULL, 1.99 ,1, 1),
('Fanta', 'Orange-flavored carbonated soft drink', NULL, 1.99,4, 4),
('Fanta', 'Orange-flavored carbonated soft drink', NULL, 1.99,4, 4),
('Fanta', 'Orange-flavored carbonated soft drink', NULL, 1.99,4, 4),
('Fanta', 'Orange-flavored carbonated soft drink', NULL, 1.99,4, 4),
('Lemonade', 'Non-carbonated sweet and sour drink', NULL, 2.49, 6, 6),
('Iced Tea', 'Sweetened tea served chilled', NULL, 2.49, 6, 6),
('Orange Juice', 'Freshly squeezed orange juice', NULL, 2.99, 7, 7),
('Apple Juice', 'Freshly squeezed apple juice', NULL, 2.99, 7, 7),
('Cranberry Juice', 'Freshly squeezed cranberry juice', NULL, 2.99, 8, 8),
('Chocolate Milk', 'Milk with chocolate flavoring', NULL, 2.49, 8, 8),
('Vanilla Milk', 'Milk with vanilla flavoring', NULL, 2.49,  9, 9),
('Vanilla Milk', 'Milk with vanilla flavoring', NULL, 2.49,  10, 10),
('Vanilla Milk', 'Milk with vanilla flavoring', NULL, 2.49,  10, 10);      

-- Burgers 9

INSERT INTO `PizzeriaMammaMia`.`Burgers` (`Burgers_name`, `Burgers_description`, `Burgers_image`, `Burgers_price`,`Orders_Order_id`, `Orders_Client_id`) VALUES 
('Cheeseburger', 'Juicy beef patty with cheese', NULL, 8.99, 3,3),
('Bacon Burger', 'Beef patty topped with cheese', NULL, 9.99, 3,3),
('Veggie Burger', 'Grilled vegetable patty sauce', NULL, 7.99,5,1),
('Mushroom Burger', 'Beef patty with mushrooms', NULL, 10.99,  6,1),
('Jalapeño Burger', 'Beef patty with jack cheese', NULL, 9.99,10,1);

INSERT INTO `PizzeriaMammaMia`.`Categories` (`Categories_names`)
VALUES
('Meat Lovers'),
('Vegetarian'),
('Hawaiian'),
('Pepperoni'),
('Seafood'),
('Margherita'),
('BBQ Chicken'),
('Mushroom'),
('Supreme'),
('Cheese');

-- Pizzas 11

INSERT INTO `PizzeriaMammaMia`.`Pizzas` (`Pizzas_name`, `Pizzas_description`, `Pizzas_image`, `Pizzas_price`,`Orders_Order_id` ,`Orders_Client_id`, `Categories_Categories_id`)
VALUES 
-- ('Margherita', 'Tomato sauce, mozzarella, basil', NULL, 8.99, 1,1,1),
('Pepperoni', 'Tomato sauce, mozzarella, pepperoni', NULL, 10.99, 1,1,2),
('Vegetarian', 'Tomato sauce, mozzarella, vegetables', NULL, 9.99, 2,2,2),
('Meat Lover', 'Tomato sauce, mozzarella, sausage, ham', NULL, 12.99,2,2,2),
('Hawaiian', 'Tomato sauce, mozzarella, ham, pineapple', NULL, 11.99,2,2,3),
('BBQ Chicken', 'BBQ sauce, mozzarella, chicken, onions', NULL, 12.99, 4,4,1),
('Mushroom', 'Tomato sauce, mozzarella, mushrooms', NULL, 9.99, 4, 4, 2),
('Supreme', 'Tomato sauce, mozzarella, sausage', NULL, 13.99, 4,4,3),
('Four Cheese', 'Tomato sauce, mozzarella, parmesan', NULL, 10.99,6,6,1 ),
('Buffalo Chicken', 'Buffalo sauce, mozzarella, chicken', NULL, 12.99,7,7,2),
('Supreme', 'Tomato sauce, mozzarella, sausage', NULL, 13.99, 7,7,3),
('Four Cheese', 'Tomato sauce, mozzarella, parmesan', NULL, 10.99,7,7,1 ),
('BBQ Chicken', 'BBQ sauce, mozzarella, chicken, onions', NULL, 12.99, 8,8,1),
('Mushroom', 'Tomato sauce, mozzarella, mushrooms', NULL, 9.99, 8, 8, 2),
('Mushroom', 'Tomato sauce, mozzarella, mushrooms', NULL, 9.99, 9, 9, 2),
('Vegetarian', 'Tomato sauce, mozzarella, vegetables', NULL, 9.99, 10,10,2),
('Meat Lover', 'Tomato sauce, mozzarella, sausage, ham, bacon', NULL, 12.99,10,10,2),
('Hawaiian', 'Tomato sauce, mozzarella, ham, pineapple', NULL, 11.99,10,10,3),
('BBQ Chicken', 'BBQ sauce, mozzarella, chicken, onions', NULL, 12.99, 10,10,1);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
